window.PROGRAMS_MANIFEST = [
  {
    id: "personal-context-program",
    projectId: "personal-context",
    name: "Personal Context",
    mode: "Research program",
    tone: "research",
    boundary: "What may the agent know, rely on, and disclose — from which evidence and under which write policy?",
    core: [
      "Evidence continuity",
      "Temporal truth",
      "Governed write-back",
      "Minimum projections",
    ],
    building: "A local graphical workbench, immutable evidence ledger, policy and projection adapters, synthetic fixtures, and longitudinal evaluation paths.",
    evidence: [
      { label: "Repository", href: "https://github.com/outisseus/personal-context" },
      { label: "Workbench", href: "https://github.com/outisseus/personal-context/tree/main/workbench" },
      { label: "Paper", href: "https://github.com/outisseus/personal-context/tree/main/papers/personal-context-and-capability-boundaries" },
    ],
  },
  {
    id: "detool-program",
    projectId: "detool",
    name: "DeTool",
    mode: "Execution system",
    tone: "execution",
    boundary: "What may the agent do in the external world, through which provider, under which authority, and with what proof?",
    core: [
      "Capability identity",
      "Provider graph",
      "Outcome verification",
      "Reliability routing",
    ],
    building: "Executable contracts, deterministic access decisions, provider routing, read-back verifiers, usage proofs, tests, and reliability history.",
    evidence: [
      { label: "Repository", href: "https://github.com/outisseus/detool" },
      { label: "Contracts", href: "https://github.com/outisseus/detool/tree/main/schemas" },
      { label: "Tests", href: "https://github.com/outisseus/detool/tree/main/tests" },
    ],
  },
];

window.PROJECTS_MANIFEST = [
  {
    id: "personal-context",
    repoSlug: "personal-context",
    name: "personal-context",
    thesis: "A research-led theory and working system for governed, source-backed internal state.",
    status: "building",
    updated: "2026-09-01",
    tags: ["Research", "AI agents", "Governed context"],
    role: "Internal-state boundary. It supplies minimum, source-backed projections and accepts verified action proofs only as candidate updates.",
    repo: "https://github.com/outisseus/personal-context",
    demo: null,
    featured: true,
  },
  {
    id: "detool",
    repoSlug: "detool",
    name: "DeTool",
    thesis: "An engineering-led execution system for authorized, verifiable external state transitions.",
    status: "building",
    updated: "2026-09-01",
    tags: ["Infrastructure", "Capabilities", "Verification"],
    role: "External-action boundary. It resolves maintained providers, verifies outcomes, and returns normalized usage proofs.",
    repo: "https://github.com/outisseus/detool",
    demo: null,
    featured: true,
  },
  {
    id: "intentgraph",
    name: "IntentGraph",
    thesis: "Natural-language intent becomes constraints, a task graph, execution, and verification.",
    status: "design",
    updated: "2026-08-26",
    tags: ["AI agents", "Planning"],
    role: "Replaceable planning layer between the internal-state and external-action boundaries.",
    repo: null,
    demo: null,
    featured: false,
  },
  {
    id: "agent-skills",
    name: "agent-skills",
    thesis: "Reusable reasoning and action workflows with sources, critics, and verification.",
    status: "experiment",
    updated: "2026-08-26",
    tags: ["AI agents", "Skills"],
    role: "Replaceable behavioral adapters rather than canonical state or capability infrastructure.",
    repo: null,
    demo: null,
    featured: false,
  },
  {
    id: "session-health-probe",
    repoSlug: "session-health-probe",
    name: "session-health-probe",
    thesis: "Explicit session states: VALID, INVALID, CHALLENGE, or PROBE_FAILURE.",
    status: "building",
    updated: "2026-08-26",
    tags: ["Reliability", "Browser automation"],
    role: "A practical reliability boundary for browser and agent execution.",
    repo: "https://github.com/outisseus/session-health-probe",
    demo: null,
    featured: true,
  },
  {
    id: "official-source-monitor",
    name: "official-source-monitor",
    thesis: "Stateful official-source deltas with cursors, coverage checks, and alerts.",
    status: "design",
    updated: "2026-08-26",
    tags: ["Information retrieval", "Monitoring"],
    role: "Source-change evidence layer.",
    repo: null,
    demo: null,
    featured: false,
  },
  {
    id: "jarvis",
    name: "Jarvis",
    thesis: "A synthetic collaborative-intelligence reference app backed by Personal Context and DeTool.",
    status: "design",
    updated: "2026-08-26",
    tags: ["AI agents", "Reference application"],
    role: "Reference application connecting governed context to authorized, verifiable action.",
    repo: null,
    demo: null,
    featured: false,
  },
  {
    id: "guatian",
    repoSlug: "guatian-mvp",
    name: "Guatian",
    thesis: "A completed narrative-mapping experiment retained as historical public work.",
    status: "inactive",
    updated: "2026-07-19",
    tags: ["Archive", "Narrative mapping"],
    role: "Inactive experiment. It is not part of the current build program.",
    repo: "https://github.com/outisseus/guatian-mvp",
    demo: "https://outisseus.github.io/guatian-mvp/",
    featured: false,
  },
  {
    id: "fuzzy-photo-search",
    name: "Fuzzy Photo Search",
    thesis: "Recover personal photos from vague memories using multimodal and metadata signals.",
    status: "experiment",
    updated: "2026-08-26",
    tags: ["Retrieval", "Local-first"],
    role: "Personal retrieval application with a local, private data path.",
    repo: null,
    demo: null,
    featured: false,
  },
  {
    id: "content-growth-engine",
    name: "Content Growth Engine",
    thesis: "Approval-first research, drafting, publishing, read-back, and telemetry.",
    status: "building",
    updated: "2026-08-26",
    tags: ["Operations", "Publishing"],
    role: "Turns engineering evidence into measurable content operations.",
    repo: null,
    demo: null,
    featured: false,
  },
  {
    id: "novel",
    name: "《天亮前，不要开灯》",
    thesis: "当 AI 成为文明操作系统，谁来决定人类何时有权看见真相？",
    status: "writing",
    updated: "2026-08-26",
    tags: ["Creative writing", "中文连载"],
    role: "技术审计员林砚追查一组跨系统重复出现的延迟可见性叙事。",
    repo: null,
    demo: "https://peaceful-relish-7e9.notion.site/nolightbeforesunrise",
    demoLabel: "阅读中文连载 ↗",
    featured: false,
  },
];
