window.PROJECTS_MANIFEST = [
  {
    id: "personal-context",
    repoSlug: "personal-context",
    name: "personal-context",
    thesis: "Governed, source-backed internal state and minimum working projections for long-running agents.",
    status: "building",
    updated: "2026-09-01",
    tags: ["AI & Agents", "Information & Retrieval", "Infrastructure"],
    role: "Internal-state boundary. It supplies evidence-backed projections to planners and accepts verified action proofs only as candidate updates.",
    repo: "https://github.com/outisseus/personal-context",
    demo: null,
    featured: true,
    cells: [["ai", "infrastructure"], ["information", "infrastructure"]],
  },
  {
    id: "detool",
    repoSlug: "detool",
    name: "DeTool",
    thesis: "A capability execution network for authorized, verifiable external state transitions.",
    status: "building",
    updated: "2026-09-01",
    tags: ["AI & Agents", "Infrastructure", "Open Networks"],
    role: "External-action boundary. It resolves maintained providers, verifies outcomes, and returns normalized usage proofs.",
    repo: "https://github.com/outisseus/detool",
    demo: null,
    featured: true,
    cells: [["ai", "infrastructure"], ["web3", "infrastructure"]],
  },
  {
    id: "intentgraph",
    name: "IntentGraph",
    thesis: "Natural-language intent becomes constraints, a task graph, execution, and verification.",
    status: "design",
    updated: "2026-08-26",
    tags: ["AI & Agents", "Infrastructure", "Planning"],
    role: "Planning and orchestration layer between internal state and external capability.",
    repo: null,
    demo: null,
    featured: false,
    cells: [["ai", "infrastructure"]],
  },
  {
    id: "agent-skills",
    name: "agent-skills",
    thesis: "Reusable reasoning and action workflows with sources, critics, and verification.",
    status: "experiment",
    updated: "2026-08-26",
    tags: ["AI & Agents", "Infrastructure", "Skills"],
    role: "Replaceable behavioral adapters rather than canonical state or capability infrastructure.",
    repo: null,
    demo: null,
    featured: false,
    cells: [["ai", "infrastructure"]],
  },
  {
    id: "session-health-probe",
    repoSlug: "session-health-probe",
    name: "session-health-probe",
    thesis: "Explicit session states: VALID, INVALID, CHALLENGE, or PROBE_FAILURE.",
    status: "building",
    updated: "2026-08-26",
    tags: ["AI & Agents", "Infrastructure", "Reliability"],
    role: "Reliability boundary for browser and agent execution.",
    repo: "https://github.com/outisseus/session-health-probe",
    demo: null,
    featured: true,
    cells: [["ai", "infrastructure"]],
  },
  {
    id: "official-source-monitor",
    name: "official-source-monitor",
    thesis: "Stateful official-source deltas with cursors, coverage checks, and alerts.",
    status: "design",
    updated: "2026-08-26",
    tags: ["Information & Retrieval", "Infrastructure", "Monitoring"],
    role: "Source-change evidence layer.",
    repo: null,
    demo: null,
    featured: false,
    cells: [["information", "infrastructure"]],
  },
  {
    id: "jarvis",
    name: "Jarvis",
    thesis: "A synthetic collaborative-intelligence reference app backed by Personal Context and DeTool.",
    status: "design",
    updated: "2026-08-26",
    tags: ["AI & Agents", "Applications", "Synthetic demo"],
    role: "Reference application connecting governed context to authorized, verifiable action.",
    repo: null,
    demo: null,
    featured: false,
    cells: [["ai", "applications"]],
  },
  {
    id: "guatian",
    repoSlug: "guatian-mvp",
    name: "Guatian",
    thesis: "Map competing narratives, actors, timelines, branches, and evidence.",
    status: "live",
    updated: "2026-07-19",
    tags: ["AI & Agents", "Information & Retrieval", "Applications"],
    role: "Live information-structure application and proof-of-work anchor.",
    repo: "https://github.com/outisseus/guatian-mvp",
    demo: "https://outisseus.github.io/guatian-mvp/",
    featured: true,
    cells: [["ai", "applications"], ["information", "applications"]],
  },
  {
    id: "fuzzy-photo-search",
    name: "Fuzzy Photo Search",
    thesis: "Recover personal photos from vague memories using multimodal and metadata signals.",
    status: "experiment",
    updated: "2026-08-26",
    tags: ["AI & Agents", "Information & Retrieval", "Applications"],
    role: "Personal retrieval application with a local, private data path.",
    repo: null,
    demo: null,
    featured: false,
    cells: [["ai", "applications"], ["information", "applications"]],
  },
  {
    id: "content-growth-engine",
    thesis: "Approval-first research, drafting, publishing, read-back, and telemetry.",
    name: "Content Growth Engine",
    status: "building",
    updated: "2026-08-26",
    tags: ["AI & Agents", "Applications", "Growth operations"],
    role: "Turns engineering evidence into measurable content operations.",
    repo: null,
    demo: null,
    featured: false,
    cells: [["ai", "applications"]],
  },
  {
    id: "novel",
    name: "《天亮前，不要开灯》",
    thesis: "当 AI 成为文明操作系统，谁来决定人类何时有权看见真相？",
    status: "writing",
    updated: "2026-08-26",
    tags: ["Creative & Writing", "Writing", "中文连载"],
    role: "技术审计员林砚追查一组跨系统重复出现的延迟可见性叙事。",
    repo: null,
    demo: "https://peaceful-relish-7e9.notion.site/nolightbeforesunrise",
    demoLabel: "阅读中文连载 ↗",
    featured: false,
    cells: [["creative", "writing"]],
  },
];

